### ISSUE TITLE
405 Error

### ISSUE THREAD

**Issue by dlg1206** [thinksabin/DTrackAuditor#13]
When testing this tool I kept running into an issue the following issue:
`response_dict = json.loads(r.text)`
I've attempted via pip and building the tool locally ( ran into the same package issue as #10 when done via docker ). After digging into the source code a bit I found that [return value](https://github.com/thinksabin/DTrackAuditor/blob/master/dtrackauditor/auditor.py#L168) was a 405 error. I'm able to use curl manually post, so it might be an outdated way of posting to Dependency Track?

## Environment
Client: virtual python environment on Ubuntu 22.04 server
Host (Running dependency track): Windows 11 hosting DT docker containers
## Full Stacktrace
![image](https://user-images.githubusercontent.com/78934662/194139478-19e0d754-523e-40c0-932a-94f5323be320.png)

**Comment by thinksabin** [comment]
hey @dlg1206 
thanks for the shout. I believe you are correct. I haven't updated this tool since a long time and I think some changes have been made in the api and dependencytrack.
I have merged the pull request from @ssavrim. I hope it will fix the issue. Unfortunately I haven't been able to test it myself but do let me know if it helped.
thanks @ssavrim for the pull request.

**Comment by thinksabin** [comment]
I have updated the code and tested on Dependencytrack v4.7. 
Please let me if know the issue still exists.
thanks again.

**Comment by ssavrim** [comment]
Hi @thinksabin ,
Ok I will test it and let you know.
Thanks
